apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-nginx-config
  namespace: ecommerce
data:
  nginx.conf: |
    user nginx;
    worker_processes 5;

    events {
      worker_connections 1000;
    }

    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;

      server {
        listen 3100;

        location = / {
          return 200 'OK';
        }

        location = /api/prom/push {
          proxy_pass http://write.ecommerce.svc.cluster.local:3100$request_uri;
        }

        location = /api/prom/tail {
          proxy_pass http://read.ecommerce.svc.cluster.local:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location ~ /api/prom/.* {
          proxy_pass http://read.ecommerce.svc.cluster.local:3100$request_uri;
        }

        location = /loki/api/v1/push {
          proxy_pass http://write.ecommerce.svc.cluster.local:3100$request_uri;
        }

        location = /loki/api/v1/tail {
          proxy_pass http://read.ecommerce.svc.cluster.local:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location ~ /loki/api/.* {
          proxy_pass http://read.ecommerce.svc.cluster.local:3100$request_uri;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-gateway
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-gateway
  template:
    metadata:
      labels:
        app: loki-gateway
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          readinessProbe:
            tcpSocket:
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 3100
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: nginx-config
          configMap:
            name: loki-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: ecommerce
spec:
  selector:
    app: loki-gateway
  ports:
    - port: 3100
      targetPort: 3100