apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: your-dockerhub-username/product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_APPLICATION_NAME
              value: product-service
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-common-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-common-secret
                  key: DB_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: app-common-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: app-common-secret
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-common-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-common-secret
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_VHOST
              valueFrom:
                secretKeyRef:
                  name: app-common-secret
                  key: RABBITMQ_VHOST
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
spec:
  selector:
    app: product-service
  ports:
    - port: 8081
      targetPort: 8081