spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/ecom-app
          jwk-set-uri: http://localhost:8443/realms/ecom-app/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080


