spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/productdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081