spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: file:/config
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888